version: '3'

services:
    reverse-proxy:
        build: ./ngix
        volumes:
            - ./ngix/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 5001:5001
            - 5002:5002
        restart: unless-stopped
    website1:
        image: php:apache
        volumes:
            - ./website1:/var/www/html
        expose:
            - 80
        depends_on:
            - reverse-proxy
    website2:
        image: php:apache
        volumes:
            - ./website2:/var/www/html
        expose:
            - 80
        depends_on:
            - reverse-proxy
